// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// jaccard_coeff
NumericMatrix jaccard_coeff(NumericMatrix idx);
RcppExport SEXP _Rphenograph_jaccard_coeff(SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_coeff(idx));
    return rcpp_result_gen;
END_RCPP
}
// jaccard_coeff_1
NumericMatrix jaccard_coeff_1(NumericMatrix idx);
RcppExport SEXP _Rphenograph_jaccard_coeff_1(SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_coeff_1(idx));
    return rcpp_result_gen;
END_RCPP
}
// jaccard_coeff_3
NumericMatrix jaccard_coeff_3(NumericMatrix idx);
RcppExport SEXP _Rphenograph_jaccard_coeff_3(SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_coeff_3(idx));
    return rcpp_result_gen;
END_RCPP
}
// jaccard_coeff_4
NumericMatrix jaccard_coeff_4(NumericMatrix idx, IntegerVector ks);
RcppExport SEXP _Rphenograph_jaccard_coeff_4(SEXP idxSEXP, SEXP ksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ks(ksSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_coeff_4(idx, ks));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rphenograph_jaccard_coeff", (DL_FUNC) &_Rphenograph_jaccard_coeff, 1},
    {"_Rphenograph_jaccard_coeff_1", (DL_FUNC) &_Rphenograph_jaccard_coeff_1, 1},
    {"_Rphenograph_jaccard_coeff_3", (DL_FUNC) &_Rphenograph_jaccard_coeff_3, 1},
    {"_Rphenograph_jaccard_coeff_4", (DL_FUNC) &_Rphenograph_jaccard_coeff_4, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rphenograph(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
